name: Busca-Imóveis
run-name: ${{ github.actor }} - Busca Imóveis Caixa

on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 5,13 * * *'

jobs:
  run_schedule:
#    runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalando Google Chrome
        uses: browser-actions/setup-chrome@v1
        run: chrome --version

      - name: instalar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: instalar os pacotes do requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip install -r requirements.txt

      - name: edit .env file
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_CLIENTE1: ${{ secrets.EMAIL_CLIENTE1 }}
        run: |
          touch .env
          echo EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}  >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo EMAIL_CLIENTE1=${{ secrets.EMAIL_CLIENTE1 }} >> .env

      - name: executar arquivo principal
        run: python scraping.py

      - name: apagando arquivo .env
        run: rm .env