name: Busca-Imóveis
run-name: ${{ github.actor }} - Busca Imóveis Caixa

on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 5,13 * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
#    runs-on: windows-latest
    strategy:
      matrix:
        firefox: [ '84.0', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest' ]
    name: Firefox ${{ matrix.firefox }} sample

    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: instalar os pacotes do requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip install -r requirements.txt

      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
            firefox-version: ${{ matrix.firefox }}
        - run: |
            echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
            ${{ steps.setup-firefox.outputs.firefox-path }} --version

      - name: edit .env file
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_CLIENTE1: ${{ secrets.EMAIL_CLIENTE1 }}
        run: |
          touch .env
          echo EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}, EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}, EMAIL_CLIENTE1=${{ secrets.EMAIL_CLIENTE1 }} >> .env

      - name: executar arquivo principal
        run: python scraping.py

      - name: apagando arquivo .env
        run: rm .env